name: Run Full Kernel Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 git curl ccache gcc flex bison bazel openssl libelf-dev zip

      # Step 3: Make the script executable
      - name: Make action.sh executable
        run: chmod +x ./action.sh

      # Step 4: Run the script
      - name: Run action.sh
        run: |
          ./action.sh sm8750 oneplus_ace5_pro sun android15 6.6 "-android15-8-g013ec21bba94-abogki383916444@DUGH"
