name: 构建内核

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: 'CPU型号'
        required: true
        default: 'sm8750'
      FEIL:
        description: '设备代号'
        required: true
        default: 'oneplus_ace5_pro'
      CPUD:
        description: 'CPU代号'
        required: true
        default: 'sun'
      ANDROID_VERSION:
        description: 'Android版本'
        required: true
        default: 'android15'
      KERNEL_VERSION:
        description: '内核版本'
        required: true
        default: '6.6'
      KERNEL_NAME:
        description: '内核名称'
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444-@DUGH'

# 添加权限配置
permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: 设置环境
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl ccache gcc flex bison openssl libelf-dev build-essential bc
        echo "CCACHE_COMPILERCHECK=%compiler% -dumpmachine; %compiler% -dumpversion" >> $GITHUB_ENV
        echo "CCACHE_NOHASHDIR=true" >> $GITHUB_ENV
        echo "CCACHE_HARDLINK=true" >> $GITHUB_ENV

    - name: 最大化构建空间
      run: |
        # 清理系统空间
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/haskell
        sudo apt clean
        sudo rm -rf /tmp/*
        
        # 创建并启用20G的swap
        sudo swapoff -a
        sudo dd if=/dev/zero of=/swapfile bs=1G count=20
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile
        
        # 显示系统资源信息
        df -h
        free -h

    - name: 安装repo工具
      run: |
        curl -s https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: 初始化工作目录
      run: |
        mkdir -p work
        mkdir -p kernel_output_dir

    - name: 同步源码
      run: |
        cd work
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git \
          -b refs/heads/oneplus/${{ github.event.inputs.CPU }} \
          -m ${{ github.event.inputs.FEIL }}.xml \
          --depth=1 --repo-url=https://gerrit.googlesource.com/git-repo
        repo sync -c -j$(nproc --all) --no-tags --force-sync

    - name: 配置SukiSU
      run: |
        cd work/kernel_platform
        curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-dev
        cd KernelSU
        KSU_VERSION=$(expr $(git rev-list --count main) "+" 10606)
        sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

    - name: 配置SUSFS
      run: |
        cd work
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}
        git clone https://github.com/ExmikoN/SukiSU_patch.git
        cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch kernel_platform/common/
        cp susfs4ksu/kernel_patches/fs/* kernel_platform/common/fs/
        cp susfs4ksu/kernel_patches/include/linux/* kernel_platform/common/include/linux/
        cp -r SukiSU_patch/other/lz4k/include/linux/* kernel_platform/common/include/linux
        cp -r SukiSU_patch/other/lz4k/lib/* kernel_platform/common/lib
        cp -r SukiSU_patch/other/lz4k/crypto/* kernel_platform/common/crypto

    - name: 应用补丁
      run: |
        cd work/kernel_platform/common
        sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
        sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
        patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true
        cp ../../SukiSU_patch/hooks/syscall_hooks.patch ./
        patch -p1 -F 3 < syscall_hooks.patch
        cp ../../SukiSU_patch/other/lz4k_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch ./
        patch -p1 -F 3 < lz4kd.patch || true

    - name: 配置内核选项
      run: |
        cd work/kernel_platform/common
        sed -i '/CONFIG_RUNTIME_TESTING_MENU is not set/a\
        CONFIG_KSU=y\
        CONFIG_KPM=y\
        CONFIG_KSU_MANUAL_HOOK=y\
        CONFIG_KSU_SUSFS=y\
        CONFIG_KSU_SUSFS_SUS_SU=n\
        CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y\
        CONFIG_KSU_SUSFS_SUS_PATH=y\
        CONFIG_KSU_SUSFS_SUS_MOUNT=y\
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y\
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y\
        CONFIG_KSU_SUSFS_SUS_KSTAT=y\
        CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n\
        CONFIG_KSU_SUSFS_TRY_UMOUNT=y\
        CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y\
        CONFIG_KSU_SUSFS_SPOOF_UNAME=y\
        CONFIG_KSU_SUSFS_ENABLE_LOG=y\
        CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y\
        CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y\
        CONFIG_KSU_SUSFS_OPEN_REDIRECT=y\
        CONFIG_CRYPTO_LZ4HC=y\
        CONFIG_CRYPTO_LZ4K=y\
        CONFIG_CRYPTO_LZ4KD=y\
        CONFIG_CRYPTO_842=y' arch/arm64/configs/gki_defconfig

    - name: 设置内核名称
      run: |
        cd work/kernel_platform
        sed -i 's/res="\$res\$(cat "\$file")"/res="${{ github.event.inputs.KERNEL_NAME }}"/g' common/scripts/setlocalversion

    - name: 构建内核
      run: |
        cd work/kernel_platform
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=dist

    - name: 打包内核
      run: |
        cd work/kernel_platform/dist
        if [ "${{ github.event.inputs.FEIL }}" = "oneplus_ace5_pro" ]; then
          git clone -b a5p https://github.com/aa123330/AnyKernel3.git --depth=1
        else
          git clone https://github.com/aa123330/AnyKernel3.git --depth=1
        fi
        rm -rf AnyKernel3/.git AnyKernel3/push.sh
        cp Image AnyKernel3/
        cd AnyKernel3
        cp /root/work/SukiSU_patch/kpm/patch_linux ./
        chmod 777 patch_linux
        ./patch_linux
        rm -rf Image && mv oImage Image
        rm -rf patch_linux
        timestamp=$(date +%Y%m%d%H%M)
        zip -r "../SuKiSu_${KSU_VERSION}_${{ github.event.inputs.FEIL }}_${timestamp}.zip" *

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: kernel-package
        path: work/kernel_platform/dist/SuKiSu_*.zip
        retention-days: 5 
